import { Router } from 'express';
import {
  checkLogin,
  clearSessionCookie,
  makeSessionToken,
  requireAdmin,
  setSessionCookie,
} from '../auth.js';
import { db, getAdminToken, regenerateAdminToken } from '../db.js';
import { defaultBrand, listBrands } from '@socia/branding';

export const adminRouter = Router();

adminRouter.post('/login', (req, res) => {
  const { user, pass } = req.body ?? {};
  if (typeof user !== 'string' || typeof pass !== 'string' || !checkLogin(user, pass)) {
    res.status(401).json({ error: 'invalid_credentials' });
    return;
  }
  setSessionCookie(res, makeSessionToken());
  res.json({ ok: true });
});

adminRouter.post('/logout', (_req, res) => {
  clearSessionCookie(res);
  res.json({ ok: true });
});

adminRouter.get('/me', requireAdmin, (_req, res) => {
  res.json({ ok: true });
});

adminRouter.get('/token', requireAdmin, (_req, res) => {
  res.json({ token: getAdminToken() });
});

adminRouter.post('/token/regenerate', requireAdmin, (_req, res) => {
  res.json({ token: regenerateAdminToken() });
});

/**
 * Brand management.
 *
 * GET  /api/admin/brand    → { brandId, available: [{ id, name }] }
 * POST /api/admin/brand    body { brandId } → 200 ok
 *
 * The brand applies to every evaluation PDF generated by this server. The
 * setting lives in the `settings` table under key `brand_id`.
 */
adminRouter.get('/brand', requireAdmin, (_req, res) => {
  const row = db
    .prepare("SELECT value FROM settings WHERE key = 'brand_id'")
    .get() as { value: string } | undefined;
  res.json({
    brandId: row?.value ?? defaultBrand.id,
    available: listBrands().map((b) => ({ id: b.id, name: b.name.short })),
  });
});

adminRouter.post('/brand', requireAdmin, (req, res) => {
  const { brandId } = req.body ?? {};
  if (typeof brandId !== 'string' || !brandId.trim()) {
    res.status(400).json({ error: 'brandId_required' });
    return;
  }
  const known = listBrands().some((b) => b.id === brandId);
  if (!known) {
    res.status(400).json({ error: 'unknown_brand' });
    return;
  }
  db.prepare(
    `INSERT INTO settings (key, value) VALUES ('brand_id', ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
  ).run(brandId);
  res.json({ ok: true, brandId });
});
