auth.method.basic = true

cache {
  job = 60 minutes
  user = 5 minutes
  organization = 5 minutes
}

analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json",
    "/opt/Cortex-Analyzers/analyzers"
  ]
}

responder {
  urls = [
    "https://download.thehive-project.org/responders.json",
    "/opt/Cortex-Analyzers/responders"
  ]
}
